#!/bin/bash

#export PUBLIC_IPV4=$(curl -s http://169.254.169.254/metadata/v1/interfaces/public/0/ipv4/address)
export PUBLIC_IPV4=65.67.51.188
export CONSUL_KEY=$(consul keygen)
service consul stop
rm -rf /var/cache/octohost/*
sudo cat > /etc/consul.d/default.json << EOL
{
  "data_dir": "/var/cache/octohost",
  "server": true,
  "bootstrap": true,
  "client_addr": "0.0.0.0",
  "advertise_addr": "$PUBLIC_IPV4",
  "datacenter": "dc1",
  "node_name": "octohost",
  "enable_syslog": true,
  "encrypt": "$CONSUL_KEY"
}
EOL
service consul start
