#!/bin/bash
/usr/local/bin/generateSelfSignedCert mastermind webhosting.coop
octo config:set whcredmine/SSL_FORCED 'true'
octo config:set whcredmine/SSL_CERTIFICATE '/etc/nginx/certs/mastermind.webhosting.coop.crt'
octo config:set whcredmine/SSL_KEY '/etc/nginx/private/mastermind.webhosting.coop.key'
/usr/local/bin/generateSelfSignedCert meirowitz webhosting.coop
octo config:set whcredmine1/SSL_FORCED 'true'
octo config:set whcredmine1/SSL_CERTIFICATE '/etc/nginx/certs/meirowitz.webhosting.coop.crt'
octo config:set whcredmine1/SSL_KEY '/etc/nginx/private/meirowitz.webhosting.coop.key'
/usr/local/bin/generateSelfSignedCert townhall webhosting.coop
octo config:set townhallnginx/SSL_FORCED 'true'
octo config:set townhallnginx/SSL_CERTIFICATE '/etc/nginx/certs/townhall.webhosting.coop.crt'
octo config:set townhallnginx/SSL_KEY '/etc/nginx/private/townhall.webhosting.coop.key'
/usr/local/bin/generateSelfSignedCert athena thalhalla.net
octo config:set athena/SSL_FORCED 'true'
octo config:set athena/SSL_CERTIFICATE '/etc/nginx/certs/athena.thalhalla.net.crt'
octo config:set athena/SSL_KEY '/etc/nginx/private/athena.thalhalla.net.key'
/usr/local/bin/generateSelfSignedCert coxack thalhalla.net
octo config:set redmine-coxack/SSL_FORCED 'true'
octo config:set redmine-coxack/SSL_CERTIFICATE '/etc/nginx/certs/coxack.thalhalla.net.crt'
octo config:set redmine-coxack/SSL_KEY '/etc/nginx/private/coxack.thalhalla.net.key'
/usr/local/bin/generateSelfSignedCert zariztest thalhalla.net
octo config:set zariztest/SSL_FORCED 'true'
octo config:set zariztest/SSL_CERTIFICATE '/etc/nginx/certs/zariztest.thalhalla.net.crt'
octo config:set zariztest/SSL_KEY '/etc/nginx/private/zariztest.thalhalla.net.key'
